site_name: Nextflow on HPC
repo_url: https://github.com/Sydney-Informatics-Hub/nextflow-hpc-workshop
repo_name: Sydney-Informatics-Hub/nextlow-hpc-workshop

nav:
  - Home: index.md
  - Set up:  setup.md
  - Part 1: #todo add numbers to lessons when it makes sense 
    - 1.0 Introduction: part1/01_0_intro.md
    - 1.1 HPC for bioinformatics workflows: part1/01_1_hpc_for_workflows.md
    - 1.2 Software is different on HPC: part1/01_2_hpc_software.md
    - 1.3 HPC architecture: part1/01_3_hpc_architecture.md
    - 1.4 Work smarter, not harder!: part1/01_4_smarter.md
    - 1.5 Running Nextflow on HPC: part1/01_5_nf_hpc.md
    - 1.6 Intro to nf-core: part1/02_1_nfcore_intro.md
    - 1.7 Running nf-core on HPC: part1/02_2_nfcore_run.md
    - 1.8 Configuring nf-core: part1/02_3_nfcore_config.md
    - 1.9 Layering Nextflow configurations: part1/02_4_nfcore_layer.md
    - 1.10 Summary: part1/03_0_outro.md
  - Part 2:
    - 2.0 Introduction: part2/20_intro.md
    - 2.1 Running a custom pipeline on HPC: part2/21_firstrun.md
    - 2.2 Monitoring workflow runs: part2/22_reporting.md
    - 2.3 HPC optimisation strategies: part2/23_strategies.md
    - 2.4 Configuring resource usage: part2/24_resourcing.md
    - 2.5 Parallelisation: part2/25_parallelisation.md
    - 2.6 Scaling up: part2/27_scale.md
    - 2.7 Summary: part2/28_outro.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
